In [2]:
import numpy as np 

In [3]:
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # Features ( Hrs Slept, Hrs Studied)
y = np.array(([92], [86], [89]), dtype=float) # Labels(Marks obtained)
c=np.amax(X,axis=0) # Normalize
print(c)
print()
X = X/c # Normalize
y = y/100
print(X)
print(y)


[3. 9.]

[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]


In [10]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x * (1 - x)

 # Variable initialization
epoch=1000 #Setting training iterations
eta =0.1 #Setting learning rate (eta)
output_neurons = 1 #number of neurons at output layer
input_neurons = 2 #number of features in data set
hidden_neurons = 3 #number of hidden layers neurons

# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) # 2x3
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons)) # 1x3
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 3x1
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)


[[0.83652039 0.19343179 0.96369459]
 [0.95696064 0.15069374 0.85471999]]
[[0.37081649 0.2887609  0.41415487]]
[[0.05786327]
 [0.26375579]
 [0.2510817 ]]
[[0.2509981]]


In [11]:
for i in range(epoch):
    #Forward Propogation
    h_ip=np.dot(X,wh) + bh # Dot product + bias
    print(h_ip)
    h_act = sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)
    
    
    #Backpropagation
 # Error at Output layer
    Eo = y-output # Error at o/p
    outgrad = sigmoid_grad(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    print("the d_output is",d_output)

# Error at Hidden later
    Eh = d_output.dot(wout.T) # .T means transpose
    hiddengrad = sigmoid_grad(h_act) # How much hidden layer wts contributed to error
    d_hidden = Eh * hiddengrad
    wout += h_act.T.dot(d_output) *eta # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *eta
    
print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)


[[1.88545739 0.56840917 1.91133792]
 [1.18130142 0.43695691 1.21023084]
 [1.84531064 0.58265519 1.94766279]]
the d_output is [[0.0566234 ]
 [0.04581277]
 [0.04984002]]
[[1.88559388 0.56953425 1.91190893]
 [1.18137447 0.43755869 1.21053655]
 [1.84544321 0.58375421 1.94821619]]
the d_output is [[0.05469392]
 [0.04416115]
 [0.0479745 ]]
[[1.88575442 0.57065837 1.91248749]
 [1.18146041 0.43815996 1.21084631]
 [1.84559913 0.58485216 1.94877684]]
the d_output is [[0.05285738]
 [0.04258869]
 [0.04620145]]
[[1.88593622 0.57177934 1.91307162]
 [1.18155771 0.43875956 1.21115905]
 [1.84577567 0.58594692 1.94934283]]
the d_output is [[0.05110937]
 [0.04109147]
 [0.0445163 ]]
[[1.88613674 0.57289531 1.91365959]
 [1.18166505 0.43935649 1.21147386]
 [1.84597038 0.58703669 1.94991251]]
the d_output is [[0.04944551]
 [0.03966564]
 [0.04291456]]
[[1.88635373 0.57400469 1.91424992]
 [1.1817812  0.43994991 1.21178993]
 [1.84618107 0.5881199  1.9504844 ]]
the d_output is [[0.04786149]
 [0.03830746]
 [0.041

[[1.89915575 0.61180693 1.93607649]
 [1.18863539 0.46017576 1.22347879]
 [1.85858622 0.62495224 1.97159071]]
the d_output is [[0.01717456]
 [0.01163123]
 [0.01247422]]
[[1.89940596 0.61240623 1.93643608]
 [1.18876939 0.46049651 1.2236714 ]
 [1.85882824 0.62553473 1.97193776]]
the d_output is [[0.01690392]
 [0.01139096]
 [0.01222682]]
[[1.89965374 0.61299765 1.93679112]
 [1.18890208 0.46081304 1.22386158]
 [1.85906789 0.62610951 1.97228041]]
the d_output is [[0.01664089]
 [0.01115734]
 [0.01198659]]
[[1.8998991  0.61358134 1.93714171]
 [1.18903348 0.46112544 1.22404938]
 [1.85930518 0.62667673 1.97261872]]
the d_output is [[0.01638519]
 [0.01093012]
 [0.01175325]]
[[1.90014205 0.61415745 1.9374879 ]
 [1.18916358 0.46143379 1.22423483]
 [1.85954012 0.62723653 1.97295278]]
the d_output is [[0.01613653]
 [0.01070905]
 [0.01152655]]
[[1.90038261 0.61472612 1.93782978]
 [1.18929241 0.46173816 1.22441796]
 [1.85977273 0.62778905 1.97328264]]
the d_output is [[0.01589465]
 [0.01049391]
 [0.011

[[1.91579204 0.64899776 1.95846901]
 [1.19754762 0.48009004 1.23547757]
 [1.8746296  0.6609556  1.99314163]]
the d_output is [[0.00616246]
 [0.00176187]
 [0.00266606]]
[[1.91588773 0.64920436 1.95859178]
 [1.1975989  0.48020075 1.23554338]
 [1.87472148 0.66115437 1.99325929]]
the d_output is [[0.00612525]
 [0.00172829]
 [0.00263428]]
[[1.91598266 0.64940933 1.95871352]
 [1.19764979 0.48031058 1.23560865]
 [1.87481262 0.66135154 1.99337596]]
the d_output is [[0.00608851]
 [0.00169514]
 [0.00260293]]
[[1.91607684 0.64961268 1.95883426]
 [1.19770026 0.48041955 1.23567338]
 [1.87490304 0.66154714 1.99349165]]
the d_output is [[0.00605225]
 [0.00166242]
 [0.002572  ]]
[[1.91617027 0.64981443 1.95895399]
 [1.19775034 0.48052767 1.23573757]
 [1.87499273 0.66174118 1.99360637]]
the d_output is [[0.00601646]
 [0.00163012]
 [0.00254148]]
[[1.91626297 0.65001461 1.95907273]
 [1.19780003 0.48063494 1.23580123]
 [1.8750817  0.66193367 1.99372014]]
the d_output is [[0.00598113]
 [0.00159824]
 [0.002

 [ 0.00059454]]
[[1.92354721 0.66601496 1.96828353]
 [1.20170662 0.48921605 1.24074195]
 [1.88204111 0.6772202  2.00250653]]
the d_output is [[ 0.00368025]
 [-0.00047381]
 [ 0.00058598]]
[[1.92358716 0.66610618 1.96833347]
 [1.20172806 0.48926503 1.24076876]
 [1.88207899 0.67730651 2.00255384]]
the d_output is [[ 0.00366989]
 [-0.0004831 ]
 [ 0.0005775 ]]
[[1.92362684 0.66619688 1.96838309]
 [1.20174936 0.48931373 1.2407954 ]
 [1.88211662 0.67739232 2.00260084]]
the d_output is [[ 0.00365961]
 [-0.00049232]
 [ 0.0005691 ]]
[[1.92366627 0.66628708 1.96843238]
 [1.20177053 0.48936216 1.24082187]
 [1.88215401 0.67747764 2.00264753]]
the d_output is [[ 0.00364942]
 [-0.00050146]
 [ 0.00056076]]
[[1.92370545 0.66637678 1.96848136]
 [1.20179156 0.48941033 1.24084816]
 [1.88219115 0.67756247 2.0026939 ]]
the d_output is [[ 0.00363932]
 [-0.00051051]
 [ 0.0005525 ]]
[[1.92374438 0.66646598 1.96853002]
 [1.20181246 0.48945822 1.24087428]
 [1.88222805 0.67764681 2.00273997]]
the d_output is [[ 0

[[1.92697925 0.67429568 1.97255957]
 [1.2035507  0.49366735 1.24303965]
 [1.88526823 0.68497722 2.00652536]]
the d_output is [[ 2.86586980e-03]
 [-1.20201086e-03]
 [-7.35134766e-05]]
[[1.92699835 0.67434585 1.9725833 ]
 [1.20356098 0.49369436 1.24305242]
 [1.88528594 0.68502357 2.00654739]]
the d_output is [[ 2.86176027e-03]
 [-1.20567051e-03]
 [-7.68018597e-05]]
[[1.92701734 0.67439581 1.97260689]
 [1.2035712  0.49372126 1.24306512]
 [1.88530355 0.68506971 2.00656928]]
the d_output is [[ 2.85767886e-03]
 [-1.20930493e-03]
 [-8.00673034e-05]]
[[1.92703622 0.67444556 1.97263036]
 [1.20358136 0.49374805 1.24307775]
 [1.88532105 0.68511565 2.00659104]]
the d_output is [[ 2.85362534e-03]
 [-1.21291432e-03]
 [-8.33099979e-05]]
[[1.92705499 0.6744951  1.97265368]
 [1.20359146 0.49377472 1.2430903 ]
 [1.88533845 0.68516139 2.00661267]]
the d_output is [[ 2.84959948e-03]
 [-1.21649887e-03]
 [-8.65301311e-05]]
[[1.92707366 0.67454444 1.97267688]
 [1.20360151 0.49380129 1.24310279]
 [1.88535574 

 [1.88635645 0.68799686 2.00787953]]
the d_output is [[ 0.00262016]
 [-0.00142042]
 [-0.0002693 ]]
[[1.92817645 0.67762913 1.97404736]
 [1.20419572 0.49546385 1.24384111]
 [1.8863678  0.68803082 2.00789368]]
the d_output is [[ 0.00261767]
 [-0.00142263]
 [-0.00027128]]
[[1.9281889  0.67766643 1.97406284]
 [1.20420243 0.49548397 1.24384946]
 [1.88637908 0.68806465 2.00790774]]
the d_output is [[ 0.00261519]
 [-0.00142482]
 [-0.00027324]]
[[1.92820129 0.6777036  1.97407824]
 [1.20420911 0.49550403 1.24385777]
 [1.8863903  0.68809835 2.00792173]]
the d_output is [[ 0.00261273]
 [-0.001427  ]
 [-0.00027519]]
[[1.9282136  0.67774064 1.97409355]
 [1.20421576 0.49552401 1.24386603]
 [1.88640145 0.68813193 2.00793563]]
the d_output is [[ 0.00261029]
 [-0.00142917]
 [-0.00027713]]
[[1.92822585 0.67777756 1.97410879]
 [1.20422237 0.49554393 1.24387424]
 [1.88641254 0.68816538 2.00794946]]
the d_output is [[ 0.00260786]
 [-0.00143132]
 [-0.00027906]]
[[1.92823803 0.67781434 1.97412394]
 [1.204228

 [1.88725563 0.69099596 2.0090046 ]]
the d_output is [[ 0.00242725]
 [-0.00159106]
 [-0.00042168]]
[[1.92918297 0.68096704 1.97530139]
 [1.20474002 0.49726731 1.24451894]
 [1.88726189 0.69102007 2.00901248]]
the d_output is [[ 0.00242594]
 [-0.00159221]
 [-0.00042271]]
[[1.92919018 0.68099427 1.97531041]
 [1.20474393 0.49728205 1.24452383]
 [1.88726811 0.69104411 2.00902032]]
the d_output is [[ 0.00242463]
 [-0.00159336]
 [-0.00042373]]
[[1.92919736 0.68102144 1.97531938]
 [1.20474783 0.49729675 1.24452869]
 [1.8872743  0.69106808 2.00902811]]
the d_output is [[ 0.00242334]
 [-0.0015945 ]
 [-0.00042475]]
[[1.92920451 0.68104854 1.97532831]
 [1.2047517  0.49731141 1.24453353]
 [1.88728045 0.69109199 2.00903587]]
the d_output is [[ 0.00242205]
 [-0.00159564]
 [-0.00042576]]
[[1.92921161 0.68107557 1.9753372 ]
 [1.20475556 0.49732604 1.24453835]
 [1.88728657 0.69111583 2.00904358]]
the d_output is [[ 0.00242077]
 [-0.00159677]
 [-0.00042677]]
[[1.92921869 0.68110254 1.97534605]
 [1.204759

[[1.92977404 0.6834942  1.97604346]
 [1.20506178 0.49863671 1.24492244]
 [1.8877551  0.69322346 2.0096386 ]]
the d_output is [[ 0.00232402]
 [-0.00168174]
 [-0.00050253]]
[[1.92977844 0.68351604 1.97604902]
 [1.20506418 0.49864856 1.24492548]
 [1.88775861 0.69324226 2.0096431 ]]
the d_output is [[ 0.0023233 ]
 [-0.00168236]
 [-0.00050309]]
[[1.92978282 0.68353785 1.97605456]
 [1.20506658 0.4986604  1.2449285 ]
 [1.88776209 0.69326103 2.00964758]]
the d_output is [[ 0.00232259]
 [-0.00168298]
 [-0.00050364]]
[[1.92978718 0.68355962 1.97606007]
 [1.20506897 0.49867221 1.24493151]
 [1.88776556 0.69327976 2.00965204]]
the d_output is [[ 0.00232189]
 [-0.0016836 ]
 [-0.00050419]]
[[1.92979153 0.68358135 1.97606556]
 [1.20507134 0.498684   1.24493451]
 [1.887769   0.69329845 2.00965647]]
the d_output is [[ 0.00232119]
 [-0.00168421]
 [-0.00050474]]
[[1.92979585 0.68360305 1.97607103]
 [1.20507371 0.49869578 1.24493749]
 [1.88777243 0.6933171  2.00966088]]
the d_output is [[ 0.00232049]
 [-0.

[[1.9301824  0.68585896 1.97656329]
 [1.20528639 0.49992146 1.24520768]
 [1.88806119 0.69523508 2.01003848]]
the d_output is [[ 0.00226227]
 [-0.00173537]
 [-0.00055047]]
[[1.93018509 0.68587752 1.97656675]
 [1.20528788 0.49993155 1.24520959]
 [1.88806304 0.6952507  2.01004096]]
the d_output is [[ 0.0022619 ]
 [-0.00173569]
 [-0.00055075]]
[[1.93018777 0.68589607 1.9765702 ]
 [1.20528937 0.49994164 1.2452115 ]
 [1.88806489 0.69526629 2.01004343]]
the d_output is [[ 0.00226153]
 [-0.00173601]
 [-0.00055103]]
[[1.93019045 0.68591459 1.97657364]
 [1.20529085 0.49995172 1.24521339]
 [1.88806672 0.69528187 2.01004588]]
the d_output is [[ 0.00226117]
 [-0.00173632]
 [-0.00055131]]
[[1.93019311 0.6859331  1.97657706]
 [1.20529232 0.49996178 1.24521529]
 [1.88806854 0.69529743 2.01004833]]
the d_output is [[ 0.00226081]
 [-0.00173663]
 [-0.00055159]]
[[1.93019576 0.68595158 1.97658048]
 [1.20529379 0.49997184 1.24521717]
 [1.88807035 0.69531297 2.01005076]]
the d_output is [[ 0.00226044]
 [-0.

[[1.93043335 0.68785416 1.97688926]
 [1.20542645 0.50100758 1.24538878]
 [1.88821889 0.69689998 2.01025581]]
the d_output is [[ 0.00223106]
 [-0.00176195]
 [-0.00057437]]
[[1.93043518 0.68787106 1.97689167]
 [1.20542748 0.50101679 1.24539012]
 [1.88821991 0.69691398 2.01025728]]
the d_output is [[ 0.00223086]
 [-0.00176211]
 [-0.00057452]]
[[1.93043701 0.68788795 1.97689407]
 [1.20542851 0.501026   1.24539146]
 [1.88822092 0.69692798 2.01025873]]
the d_output is [[ 0.00223066]
 [-0.00176228]
 [-0.00057468]]
[[1.93043883 0.68790484 1.97689647]
 [1.20542953 0.50103519 1.2453928 ]
 [1.88822193 0.69694196 2.01026018]]
the d_output is [[ 0.00223046]
 [-0.00176245]
 [-0.00057483]]
[[1.93044064 0.68792171 1.97689885]
 [1.20543055 0.50104438 1.24539414]
 [1.88822293 0.69695593 2.01026163]]
the d_output is [[ 0.00223027]
 [-0.00176261]
 [-0.00057497]]
[[1.93044245 0.68793857 1.97690123]
 [1.20543157 0.50105357 1.24539547]
 [1.88822393 0.69696989 2.01026306]]
the d_output is [[ 0.00223007]
 [-0.